name: Remote Echidna 

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      project_git_url:
        required: true
        type: string
      project_git_checkout:
        required: true
        type: string
      s3_bucket:
        required: true
        type: string
      ec2_instance_key_name:
        required: true
        type: string
      run_tests_cmd:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true


jobs:
  remote-echidna:
    name: Run remote-echidna
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: remote-echidna
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Create tfvars file
        run: |
          echo 'project = "${{ inputs.project }}"' >> ${{ inputs.project }}.tfvars
          echo 'project_git_url = "${{ inputs.project_git_url }}"' >> ${{ inputs.project }}.tfvars
          echo 'project_git_checkout = "${{ inputs.project_git_checkout }}"' >> ${{ inputs.project }}.tfvars
          echo 's3_bucket = "${{ inputs.s3_bucket }}"' >> ${{ inputs.project }}.tfvars
          echo 'ec2_instance_key_name = "${{ inputs.ec2_instance_key_name }}"' >> ${{ inputs.project }}.tfvars
          echo 'run_tests_cmd = "${{ inputs.run_tests_cmd }}"' >> ${{ inputs.project }}.tfvars
      - name: Provision
        run: ./scripts/provision.sh ${{ inputs.s3_bucket }} ${{ inputs.project_git_checkout }}
      - name: Destroy previous instance
        run: |
          terraform init
          terraform destroy -target aws_instance.ec2_instance -var-file ${{ inputs.project }}.tfvars -no-color -input=false -auto-approve
      - name: Terraform Apply
        id: apply
        run: |
          terraform init
          terraform apply -var-file ${{ inputs.project }}.tfvars -no-color -input=false -auto-approve
          EC2_INSTANCE_ID=$(terraform output ec2_instance_id)
          echo "EC2_INSTANCE_ID=${EC2_INSTANCE_ID}" >> $GITHUB_OUTPUT
      - name: Provisioned
        run: ./scripts/provisioned.sh ${{ inputs.s3_bucket }} ${{ inputs.project_git_checkout }} ${{ steps.apply.outputs.EC2_INSTANCE_ID }}

